<!DOCTYPE html>
<html>

<body>
    <table>
        <tr>
            <td colspan="2">
                <h3><?= $data['heading']; ?> Course Enquiry</h3>
            </td>
        </tr>

        <tr>
            <td>Name: </td>
            <td>
                <?= $data['name']; ?>
            </td>
        </tr>
        <tr>
            <td>Email: </td>
            <td>
                <?= $data['email']; ?>
            </td>
        </tr>
        <tr>
            <td>Phone No: </td>
            <td>
                <?= $data['number']; ?>
            </td>
        </tr>
        <tr>
            <td>Emergency No: </td>
            <td>
                <?= $data['emer']; ?>
            </td>
        </tr>


    </table>

</body>

</html>